In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Data/Credit+Card+Dashboard.xlsx')

In [8]:
df.head()

,Company,Company public response,Company response to consumer,Complaint Category,Complaint ID,Consumer complaint narrative,Consumer consent provided?,Consumer consent provided? (group),Consumer disputed?,Date received,...,Sub-issue,Sub-product,Submitted via,Table Name,Tags,Timely response?,ZIP code,Avg No of days,donut,Number of Records
0,Synchrony Financial,NaN,Closed with non-monetary relief,Billing disputes,1118322,NaN,NaN,Other Includes Null,No,2018-11-15,...,NaN,NaN,Web,Credit_Card_Complaints.csv,Older American,Yes,30024.0,0,0,1
1,JPMorgan Chase & Co.,NaN,Closed with explanation,Closing/Cancelling account,1111301,NaN,NaN,Other Includes Null,No,2018-11-11,...,NaN,NaN,Web,Credit_Card_Complaints.csv,NaN,Yes,6606.0,0,0,1
2,Sterling Jewelers Inc.,NaN,Closed with explanation,Bankruptcy,1118893,NaN,NaN,Other Includes Null,Yes,2018-11-16,...,NaN,NaN,Web,Credit_Card_Complaints.csv,NaN,Yes,54935.0,0,0,1
3,Citibank,NaN,Closed with explanation,Billing disputes,1097558,NaN,NaN,Other Includes Null,Yes,2018-11-02,...,NaN,NaN,Web,Credit_Card_Complaints.csv,NaN,Yes,5150.0,0,0,1
4,Discover,NaN,Closed with explanation,Billing disputes,1106302,NaN,NaN,Other Includes Null,No,2018-11-06,...,NaN,NaN,Web,Credit_Card_Complaints.csv,NaN,Yes,60646.0,0,0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86893 entries, 0 to 86892
Data columns (total 25 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Company                             86893 non-null  object
 1   Company public response             19745 non-null  object
 2   Company response to consumer        86893 non-null  object
 3   Complaint Category                  86893 non-null  object
 4   Complaint ID                        86893 non-null  int64
 5   Consumer complaint narrative        17285 non-null  object
 6   Consumer consent provided?          29320 non-null  object
 7   Consumer consent provided? (group)  86893 non-null  object
 8   Consumer disputed?                  83121 non-null  object
 9   Date received                       86893 non-null  datetime64[ns]
 10  Date sent to company2               86893 non-null  datetime64[ns]
 11  Dimension                           86893 non-null  object
 12  Issue                               86893 non-null  object
 13  Product                             86893 non-null  object
 14  State                               86155 non-null  object
 15  Sub-issue                           0 non-null      float64
 16  Sub-product                         0 non-null      float64
 17  Submitted via                       86892 non-null  object
 18  Table Name                          86893 non-null  object
 19  Tags                                13097 non-null  object
 20  Timely response?                    86893 non-null  object
 21  ZIP code                            67806 non-null  float64
 22  Avg No of days                      86893 non-null  int64
 23  donut                               86893 non-null  int64
 24  Number of Records                   86893 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(4), object(16)
memory usage: 16.6+ MB

In [5]:
df["Company public response"].value_counts()

Company public response
Company has responded to the consumer and the CFPB and chooses not to provide a public response                            12343
Company chooses not to provide a public response                                                                            6313
Company believes it acted appropriately as authorized by contract or law                                                     837
Company believes complaint is the result of an isolated error                                                                123
Company believes complaint represents an opportunity for improvement to better serve consumers                                44
Company believes the complaint is the result of a misunderstanding                                                            32
Company can't verify or dispute the facts in the complaint                                                                    20
Company disputes the facts presented in the complaint                                                                         17
Company believes complaint caused principally by actions of third party outside the control or direction of the company       15
Company believes complaint relates to a discontinued policy or procedure                                                       1
Name: count, dtype: int64

In [6]:
df["Company response to consumer"].value_counts()

Company response to consumer
Closed with explanation            51873
Closed with monetary relief        17942
Closed with non-monetary relief     9215
Closed without relief               4246
Closed with relief                  2500
Closed                               649
In progress                          329
Untimely response                    139
Name: count, dtype: int64

In [7]:
df["Date received"].value_counts()

Date received
2016-06-19    259
2016-06-20    140
2015-12-05    139
2016-05-15    131
2020-09-09    119
             ...
2021-04-01      2
2021-04-10      2
2018-07-13      1
2021-04-09      1
2021-04-07      1
Name: count, Length: 1956, dtype: int64